### ISSUE TITLE
Incorrect battery power calculation

### ISSUE THREAD

**Issue by andreondra** [andreondra/homeassistant-sermatec-inverter#12]
Battery power is not calculated properly when the current is lower than 1 (floating type error = fix types, use float explicitly).

**Comment by mathieupotier** [comment]
I suggest this:
power (int) = ceil((int)voltage * (float) current)

Can you just confirm that the current value is coming as a float ?

**Comment by andreondra** [comment]
Yes, both voltage and current are floats rounded to 1 decimal place, thus we shouldn't reduce precision where it's not necessary - I left the calculations and also the result as a float.
