### ISSUE TITLE
inversion on discharging and charging battery power

### ISSUE THREAD

**Issue by mathieupotier** [andreondra/homeassistant-sermatec-inverter#16]
Hi there,

Battery is showing discharging power value instead of charging power value :
![image](https://user-images.githubusercontent.com/10141454/211304110-34a78d15-d321-42fb-9621-f9b9c7531103.png)

Formula for power in Direct Current context : P(Watts) = I(Ampers) * U(Volts)

Negative Watt value mean battery is charging
Positive Watt value mean battery is discharging.

Regards

**Comment by andreondra** [comment]
That's weird, for me it shows the correct values with the current formula - negative current means the battery is discharging. It probably depends on the type of the battery, which the official app can check and then apply the correct formula. I have the Pylontech hi-voltage ones, what type do you use?

**Comment by mathieupotier** [comment]
@andreondra
I have this material :
![IMG_0027](https://user-images.githubusercontent.com/10141454/213127209-ec2989c6-a618-4bed-a0fe-59b4baab8ed8.jpg)

Maybe some setup on inverter, or firmware version related.

**Comment by mathieupotier** [comment]
Seems the battery state information is relevant ... maybe relying on this should do the trick ...
![image](https://user-images.githubusercontent.com/10141454/213146356-75fc8b0c-be64-43cb-8b27-1bab240a65f8.png)

**Comment by andreondra** [comment]
That's a good idea. The battery state has a dedicated field in the communication protocol and it should always be correct, unlike the current sign which probably depends on a battery type as we saw.
