### ISSUE TITLE
solar_inverter_battery_temperature wrong unit

### ISSUE THREAD

**Issue by andreondra** [andreondra/homeassistant-sermatec-inverter#18]
In the newest version the Home Assistant reports:

`Entity sensor.solar_inverter_battery_temperature (<class 'custom_components.sermatec_inverter.sensor.SermatecSensor'>) is using native unit of measurement '˚C' which is not a valid unit for the device class ('temperature') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.`

**Comment by mathieupotier** [comment]
Seems related to this documentation : https://developers.home-assistant.io/docs/core/entity/sensor

**Comment by mathieupotier** [comment]
Issue spotted, the char used in unit string was not the good one, PR on the way ...
