### ISSUE TITLE
After installing the Home Assistant Core Update 2023.5.0, the integration stops working

### ISSUE THREAD

**Issue by MildaC** [andreondra/homeassistant-sermatec-inverter#29]
After installing the Home Assistant Core Update 2023.5.0, the integration stops working. It does not load entities.

**Comment by andreondra** [comment]
Thanks for the info, I'll have a look at it.

**Comment by mathieupotier** [comment]
`ˋˋ2023-05-04 15:50:51.177 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration sermatec_inverter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-04 15:51:34.078 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Sermatec Inverter for sermatec_inverter
File "/config/custom_components/sermatec_inverter/__init__.py", line 35, in async_setup_entry`ˋˋ

here are logs…

**Comment by MildaC** [comment]
more info probably here https://github.com/home-assistant/core/pull/91929

**Comment by andreondra** [comment]
Thanks guys, hopefully this weekend I'll have some time to fix this issue.

**Comment by andreondra** [comment]
Platform loading should be changed to fix this issue: https://developers.home-assistant.io/docs/config_entries_index#for-platforms
