### ISSUE TITLE
Error unit type reactive and apparent power

### ISSUE THREAD

**Issue by geof6298** [andreondra/homeassistant-sermatec-inverter#50]
Hello,

il y a une erreur sur la puissance réactive qui est en VAR et non en W.
sur la puissance apparente qui est en VA et non en VAR.

une petite correction :-)

Bonne Journée

**Comment by mathieupotier** [comment]
hi @geof6298 

Je pense que c'est bon en fait ... de ce que je me souviens de mes cours de physique :
Puissante apparente VA
Puissance réactive VAR
Puissance active W

^_^

**Comment by mathieupotier** [comment]
![image](https://github.com/sermatec-opensource/homeassistant-sermatec-inverter/assets/10141454/adcb21e5-622f-41d5-9523-4b0c516949cf)

**Comment by mathieupotier** [comment]
ouais même ce schema est ambigue ...
Mais je te confirme que :
 - puissance apparente VA (VoltAmpère)
 - puissance réactive VAr ou VAR - on peut voir les deux - (VoltAmpère Réactif)
 - puissance active en W (Watt)

**Comment by geof6298** [comment]
dans le fichier protocole-en.json
![image](https://github.com/sermatec-opensource/homeassistant-sermatec-inverter/assets/135816266/0f388ccc-752b-4529-8863-0fb39441b4e1)

et sur mon tableau de bord

![image](https://github.com/sermatec-opensource/homeassistant-sermatec-inverter/assets/135816266/9541a108-f80d-4f4d-9499-b6a36ae50945)

il n'y a pas les bonnes unités

;-)

**Comment by mathieupotier** [comment]
ah ok ... dsl j'avais pas compris ... ^_^

**Comment by geof6298** [comment]
je me suis peut être mal exprimé aussi lol

**Comment by mathieupotier** [comment]
@andreondra 

Seems that there is a mistake on unit used in protocol-en.json
Should it be fixed in the file ? or it is generated from the sermatec one ?

**Comment by mathieupotier** [comment]
@andreondra Seems that it comes with error even in original repository ...

**Comment by andreondra** [comment]
It can be fixed in the file, it's not generated. It's probably a mistake present also in the app :D

**Comment by mathieupotier** [comment]
this repo will be the future truth source for sermatec ... ^_^
