### ISSUE TITLE
Test parameter setting

### ISSUE THREAD

**Issue by andreondra** [andreondra/homeassistant-sermatec-inverter#60]
Hi @mathieupotier,

finally, it is possible to configure basic parameters by this integration. When you have time, can you please test this feature on your inverter? If you encounter no errors, we can finally release a v2.1.0! Note that there will be slight delay (up to 1 min) between toggling the value and state update... This is expected and described in README.

**Comment by mathieupotier** [comment]
@andreondra assign this issue to me ...
I'll try to deploy this on my installation in the next few days ...

**Comment by mathieupotier** [comment]
deployed this branch on my integration, seems ok, I'll let it run for a couple of hours, and let you know if I had any error message in logs

**Comment by mathieupotier** [comment]
seems ok, no significant errors raised after 24h

**Comment by andreondra** [comment]
Great! We are ready for new release then.
