### ISSUE TITLE
Login in..

### ISSUE THREAD

**Issue by WitoldPalowski** [andreondra/homeassistant-sermatec-inverter#9]
Hi, 
I've used your way to integrate Sermatec. I can see Sermatec Inverter in possible integrations in HA, but when I choose it, I am stucked now here. What should be filled in?
![PrintScreen](https://user-images.githubusercontent.com/113245361/191180729-12c78a4f-bd70-41b4-b42b-242abf4195ed.JPG)

**Comment by andreondra** [comment]
Hello, thank you for your report. Please, try the latest version, it is probably an issue with language files. First input box is an IP address of your inverter and the second is a port, you can fill in the default, which is 8899.

If the issue persists, please let me know.

**Comment by WitoldPalowski** [comment]
Thanks. I can see already host = IP and port. It is important to remark, it is inverter's IP of STxxxx wifi. In my case 10.10.100.254. And I had to set up my WLAN connection on HA properly first. HA is set up that Cable LAN is on my main network and WLAN on inverter's wifi STxxxx.

**Comment by andreondra** [comment]
Actually it is not needed to connect to the inverter's WiFi (although it is possible of course). If you connected the inverter to your home WiFi (the embedded UART bridge can work both in station and AP modes), it will be available in the local network for connection. Then the inverter's IP is determined by the local DHCP server.
